# Goal: PR Checks

on: 
  pull_request:
    branches: [main]

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR is running for which branch
        run: echo "PR check running for branch: ${{ github.ref_name }}"
